import jsf from 'json-schema-faker';
import {createElement} from 'react';

function fakeFunction() {
  var args = Array.prototype.slice.call(arguments);
  console && console.log && console.log("Autogenerated function called with arguments", args); // eslint-disable-line no-console
}

jsf.extend('faker', (faker) => {
  faker.type = function(name) {
    switch(name) {
      case 'function':
        return fakeFunction;
      case 'element':
        return createElement('div', {
          style: { backgroundColor: '#aaa', padding: '1em' }
        }, 'Placeholder');
    }

    return null;
  };

  return faker;
});

export default function fake(schema) {
  return jsf(schema);
}
